#!/bin/sh


ssh jenkins@54.64.212.101 -t -t << EOF
	test -d nodeRepo && cd nodeRepo && git pull || git clone https://github.com/NourritureGroup1/superphung.git nodeRepo && cd nodeRepo
	npm install --production
	forever restartall
	exit
EOF
